[project]
name = "hass-teleco-daisy"
version = "0.1.2"
description = "Home Assistant custom component for Teleco Automation Daisy"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "teleco-daisy>=0.1.2",
]

[dependency-groups]
dev = [
    "homeassistant>=2023.7.3",
    "ruff>=0.12.4",
]
