[tool.poetry]
name = "hass-teleco-daisy"
version = "0.1.0"
description = "Home Assistant custom component for Teleco Automation Daisy"
authors = []
license = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
teleco_daisy = "^0.1.0"


[tool.poetry.group.dev.dependencies]
homeassistant = ">2023"
black = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
