target-version = "py311"
exclude = [
    ".venv",
    ".eggs",
    ".git",
    ".github",
]

[lint]
select = [
    "B",
    "C",
    "E",
    "W",
    "F",
    "FLY",
    "DJ",
    "I",
    "N",
    "S",
    "PLC",
    "RUF",
    "UP",
]
